plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.audiodsp'
version = '1.0.0'

android {
  namespace "expo.modules.audiodsp"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
    consumerProguardFiles 'consumer-rules.pro'
  }

  dependencies {
    implementation 'androidx.media3:media3-common:1.9.0'
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}
